### CX Maximum finden

In [1]:
#Lösungsvariante max einer liste ohne max()
def max_liste(liste):
    if len(liste) == 0:
        return None  # Rückgabe von None für eine leere Liste
    max_wert = liste[0]  # Initialisiere max_wert mit dem ersten Element der Liste
    for zahl in liste:
        if zahl > max_wert:
            max_wert = zahl  # Aktualisiere max_wert, wenn eine größere Zahl gefunden wird
    return max_wert

# Repetiotionsquiz aufgaben

In [ ]:
# 30 sekunden
l=[3, 1, 4, 1, 5, 9]
print(l.sort())
print(l[::-1])
print(type(l))
print(dir(l))

In [ ]:
#30 sekunden
x=[1, 2, 3,4]
y=[4, 5, 6]
print(list(zip(x,y)))

In [ ]:
#am besten mit notizen lösen, 1-2 minuten
l=[3, 1,5]
n = 2
d={8000:'zurich'}
for i in range(n + len(l)):
    print(l[i % len(l)])
    key=l[i % len(l)]
    d[key]=i
print(d)  

In [ ]:
y=[4, 5, 6]
z=y
z[0]=10
print(z==y)

# Comprehensions

In [6]:
#mit for schleife eine list von 1 bis 10 erstellen
liste = []
for i in range(1, 11):
    liste.append(i)
print('using default for loop',liste)

#now with list comprehension
liste = [i for i in range(1, 11)]
print('using list comprehension', liste)

using default for loop [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
using list comprehension [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# Dicitionaries

In [14]:

#dicitonary anhand eines instagram profils
ethz_ig_profile = {
    'username': 'ETH Zurich',
    'followers': 139000,
    'following': 346,
    'posts': 1893,
    'bio': 'where the future begins etc..'
}

#wert eines keys ausgeben
print(ethz_ig_profile['username'])

##neue key value pair hinzufügen
#ethz_ig_profile['website'] = 'https://ethz.ch'

##update followers
#ethz_ig_profile['followers'] = 140000

##prüfen ob ein key in einem dictionary existiert
#'followers' in ethz_ig_profile

##ein key value pair löschen
#del ethz_ig_profile['following']

ETH Zurich


In [ ]:
#über das dict iterieren
for key in ethz_ig_profile:
    print(key,' : ', ethz_ig_profile[key])
print('\n')

#alternativ
for key, value in ethz_ig_profile.items():
    print(key,' : ', value)
print('\n')

#oder nur die values
for value in ethz_ig_profile.values():
    print(value)

In [10]:
#hdi over the last 5 years in switzerland, values in a list, years in another list

years = [2016, 2017, 2018, 2019,2020,2021,2022,2023,2024,2025]
hdi_values = [ 0.96, 0.97, 0.98, 0.99,]    

#dictionary erstellen, in dem die jahre die keys sind und die hdi werte die values using zip
hdi_dict = dict(zip(years, hdi_values))
print('old hdi: ', hdi_dict,)


#dict comprehension nutzen um die hdi werte zu erhöhen um 0.01
hdi_dict = {year: hdi + 0.01 for year, hdi in hdi_dict.items()}
print('corrected hdi_dict with .items: ', hdi_dict,)

#dict comprehension mit zip() nutzen um die hdi werte zu erhöhen um 0.01
hdi_dict = {year: hdi + 0.01 for year, hdi in zip(years, hdi_values)}
print('corrected hdi_dict with zip: ', hdi_dict,)

old hdi:  {2016: 0.96, 2017: 0.97, 2018: 0.98, 2019: 0.99}
corrected hdi_dict with .items:  {2016: 0.97, 2017: 0.98, 2018: 0.99, 2019: 1.0}
corrected hdi_dict with zip:  {2016: 0.97, 2017: 0.98, 2018: 0.99, 2019: 1.0}


# Aliasing / Pointer demos

In [ ]:
#is the is operator the same as the == operator?
a = [47.3769, 8.5417] #coordinate of zurich
b = a
print( (id(a)==id(b)) == (a is b) ) 

True


In [20]:

#a tuple is immutable, a list is mutable
# elements of a list within a tuple can be changed, but the tuple itself cannot be changed
my_tuple = (1, 2, [3, 4])
print('previous id(my_tuple[2]):', id(my_tuple[2]))
my_tuple[2][0] = 10
print(my_tuple)
print('(still same) id(my_tuple[2]):', id(my_tuple[2]))

previous id(my_tuple[2]): 4539919808
(1, 2, [10, 4])
(still same) id(my_tuple[2]): 4539919808


# Numpy

In [13]:
import numpy as np

#arange syntax: 
#np.arange(start, stop, step) # type: ignore
print(np.arange(0, 10, 2)) #0, 2, 4, 6, 8

#numpy linspace: 
#np.linspace(start, stop, num) #default value num=50   # type: ignore
print(np.linspace(0, 10, 11))


[0 2 4 6 8]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# "list slicing" in numpy two-dimensional arrays
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#general syntax including step: 

#new_array=array[start_row:end_row:row_step, start_col:end_col:col_step] # type: ignore

#example using all parameters
print(a[0:3:1, 0:3:2]) 


[[1 3]
 [4 6]
 [7 9]]


# Recursion example

In [ ]:
def factorial(n):
    if n == 0: #base case, we know that 0! is 1
        return 1
    else:
        return n * factorial(n - 1)

# any() function

In [10]:
#exmaple of the any function
numbers = [1, 2, 3, 4, 5]
print(any(num > 3 for num in numbers))  # True, because 4 and 5 are greater than 3

True
